Repository agerard57/TS_React-Kanban, pull requests merged in 2023-01, with the labels that each got.

#1 Feature: Create landing page
  client/src/App.css
  client/src/core/assets/EnglishFlag.svg
  client/src/core/assets/FrenchFlag.svg
  client/src/core/components/ColoredBackground.tsx
  client/src/core/components/LandscapeMode.tsx
  client/src/core/components/Layout.tsx
  client/src/core/components/Mobile.tsx
  client/src/core/components/Navbar.tsx
  client/src/core/components/index.ts
  client/src/core/hooks/index.ts
  client/src/core/hooks/useCustomToast.ts
  client/src/core/hooks/usePageTitle.ts
  client/src/core/i18n/en.json
  client/src/core/i18n/fr.json
  client/src/core/index.ts
  client/src/core/language/hooks/useLanguage.ts
  client/src/i18n/resources.ts
  client/src/landingPage/assets/.gitkeep
  client/src/landingPage/components/LandingPage.tsx
  client/src/landingPage/components/index.ts
  client/src/landingPage/helpers/.gitkeep
  client/src/landingPage/hooks/index.ts
  client/src/landingPage/hooks/useLandingPage.tsx
  client/src/landingPage/i18n/en.json
  client/src/landingPage/i18n/fr.json
  client/src/landingPage/i18n/index.ts
  client/src/landingPage/index.ts
  client/src/landingPage/interfaces/.gitkeep
  client/src/landingPage/services/.gitkeep
  client/src/routeManager/components/RouteManager.tsx
  scripts/generate_new_package.py
  ts-kanban.code-workspace
Labels: feature, front-end

#3 Feature: Create table
  client/src/App.css
  client/src/core/components/ColorVignette.tsx
  client/src/core/components/Navbar.tsx
  client/src/core/components/TextInput.tsx
  client/src/core/components/index.ts
  client/src/core/components/kanban/KanbanCard.tsx
  client/src/core/components/kanban/KanbanList.tsx
  client/src/core/components/kanban/index.ts
  client/src/core/i18n/en.json
  client/src/core/i18n/fr.json
  client/src/core/index.ts
  client/src/core/types/Card.ts
  client/src/core/types/List.ts
  client/src/core/types/User.ts
  client/src/core/types/index.ts
  client/src/landingPage/components/AddList.tsx
  client/src/landingPage/components/LandingPage.tsx
  client/src/landingPage/components/UserList.tsx
  client/src/landingPage/i18n/en.json
  client/src/landingPage/i18n/fr.json
  docs/KanBan.postman_collection.json
  ts-kanban.code-workspace
Labels: feature, front-end

#4 04/01 - Prod release
  api/src/controllers/card.controller.js
  api/src/controllers/genericCRUDController.js
  api/src/controllers/list.controller.js
  api/src/controllers/user.controller.js
  api/src/factory/CrudFactory.js
  api/src/middleware/auth.middleware.js
  api/src/routes/card.routes.js
  api/src/routes/list.routes.js
  api/src/routes/user.routes.js
  api/src/services/userService.js
  client/src/App.css
  client/src/core/assets/EnglishFlag.svg
  client/src/core/assets/FrenchFlag.svg
  client/src/core/components/ColorVignette.tsx
  client/src/core/components/ColoredBackground.tsx
  client/src/core/components/LandscapeMode.tsx
  client/src/core/components/Layout.tsx
  client/src/core/components/Mobile.tsx
  client/src/core/components/Navbar.tsx
  client/src/core/components/TextInput.tsx
  client/src/core/components/index.ts
  client/src/core/components/kanban/KanbanCard.tsx
  client/src/core/components/kanban/KanbanList.tsx
  client/src/core/components/kanban/index.ts
  client/src/core/hooks/index.ts
  client/src/core/hooks/useCustomToast.ts
  client/src/core/hooks/usePageTitle.ts
  client/src/core/i18n/en.json
  client/src/core/i18n/fr.json
  client/src/core/index.ts
  client/src/core/language/hooks/useLanguage.ts
  client/src/core/types/Card.ts
  client/src/core/types/List.ts
  client/src/core/types/User.ts
  client/src/core/types/index.ts
  client/src/i18n/resources.ts
  client/src/landingPage/assets/.gitkeep
  client/src/landingPage/components/AddList.tsx
  client/src/landingPage/components/LandingPage.tsx
  client/src/landingPage/components/UserList.tsx
  client/src/landingPage/components/index.ts
  client/src/landingPage/helpers/.gitkeep
  client/src/landingPage/hooks/index.ts
  client/src/landingPage/hooks/useLandingPage.tsx
  client/src/landingPage/i18n/en.json
  client/src/landingPage/i18n/fr.json
  client/src/landingPage/i18n/index.ts
  client/src/landingPage/index.ts
  client/src/landingPage/interfaces/.gitkeep
  client/src/landingPage/services/.gitkeep
  client/src/routeManager/components/RouteManager.tsx
  docs/KanBan.postman_collection.json
  scripts/generate_new_package.py
  ts-kanban.code-workspace
Labels: PROD

#9 Feature: Initialize backend tests
  api/test/Cards/index.js
  api/test/Lists/createList.test.js
  api/test/Lists/deleteList.test.js
  api/test/Lists/index.js
  api/test/index.js
Labels: back-end

#11 Feature: Initialize tests
  .github/workflows/build.yml
  .vscode/settings.json
  api/.vscode/settings.json
  api/package.json
  client/.eslintignore
  client/.eslintrc
  client/assetsTransformer.js
  client/babel.config.js
  client/jest.config.js
  client/jest.setup.js
  client/package.json
  client/public/index.html
  client/scripts/test.js
  client/src/App.test.tsx
  client/src/core/components/index.ts
  client/src/core/index.ts
  client/src/landingPage/i18n/en.json
  client/src/react-app-env.d.ts
  client/tsconfig.json
  sonar-project.properties
Labels: front-end

#18 Feature: Card details
  client/src/App.tsx
  client/src/cardDetailsModal/assets/.gitkeep
  client/src/cardDetailsModal/components/CardDetailsModal.tsx
  client/src/cardDetailsModal/components/CardDetailsModalBuilder.tsx
  client/src/cardDetailsModal/components/index.ts
  client/src/cardDetailsModal/helpers/.gitkeep
  client/src/cardDetailsModal/hooks/index.ts
  client/src/cardDetailsModal/hooks/useCardDetailsModalBuilder.tsx
  client/src/cardDetailsModal/i18n/en.json
  client/src/cardDetailsModal/i18n/fr.json
  client/src/cardDetailsModal/i18n/index.ts
  client/src/cardDetailsModal/index.ts
  client/src/cardDetailsModal/interfaces/.gitkeep
  client/src/cardDetailsModal/services/.gitkeep
  client/src/core/components/Layout.tsx
  client/src/core/components/index.ts
  client/src/core/components/inputs/Button.tsx
  client/src/core/components/inputs/TextInput.tsx
  client/src/core/components/inputs/index.ts
  client/src/core/components/kanban/KanbanCard.tsx
  client/src/core/index.ts
  client/src/i18n/resources.ts
  client/src/index.css
  client/src/landingPage/components/AddList.tsx
  client/src/modal/components/Button.tsx
  client/src/modal/components/EmptyModal.tsx
  client/src/modal/components/Modal.tsx
  client/src/modal/components/ModalProvider.tsx
  client/src/modal/components/index.ts
  client/src/modal/contexts/ModalContext.ts
  client/src/modal/contexts/index.ts
  client/src/modal/hooks/index.ts
  client/src/modal/hooks/useModal.tsx
  client/src/modal/hooks/useModalManager.tsx
  client/src/modal/index.ts
  client/src/modal/styles/index.ts
  client/src/modal/styles/modalStyles.ts
  client/src/modal/types/SlideSpec.ts
  client/src/modal/types/UseModalManager.ts
  client/src/modal/types/index.ts
Labels: feature, front-end

#15 Feature: User tests
  .github/workflows/api-checks.yml
  .gitignore
  api/package.json
  api/src/models/user.model.js
  api/test/Lists/createList.test.js
  api/test/Lists/index.js
  api/test/Users/connectUser.test.js
  api/test/Users/createUser.test.js
  api/test/Users/index.js
  api/test/cookie/.gitkeep
  api/test/index.js
  api/test/setupTest.js
  docs/KanBan.postman_collection.json
Labels: back-end, shite

#22 Develop production
  api/src/config/database.config.js
  api/src/controllers/genericCRUDController.js
  api/test/cookie/.gitkeep
  api/test/index.js
  api/test/setupTest.js
  client/.eslintignore
  client/.prettierignore
  client/src/authPages/components/RegisterPage.tsx
  client/src/cardDetailsModal/assets/.gitkeep
  client/src/cardDetailsModal/helpers/.gitkeep
  client/src/cardDetailsModal/interfaces/.gitkeep
  client/src/cardDetailsModal/services/.gitkeep
  client/src/core/components/Button.tsx
  client/src/core/components/Navbar.tsx
  client/src/core/i18n/en.json
  client/src/core/i18n/fr.json
  client/src/landingPage/assets/.gitkeep
  client/src/landingPage/components/LandingPage.tsx
  client/src/landingPage/helpers/.gitkeep
  client/src/landingPage/hooks/useLandingPage.tsx
  client/src/landingPage/interfaces/.gitkeep
  client/src/landingPage/services/.gitkeep
  client/src/modal/styles/modalStyles.ts
  docs/FUNCTIONAL_DOCUMENTATION.md
  package.json
Labels: PROD
